# This file was generated by GoReleaser. DO NOT EDIT.
cask "hulak" do
  name "hulak"
  desc "File based API client for terminal nerds"
  homepage "https://github.com/xaaha/hulak"
  version "0.2.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hulak"
  manpage "man/hulak.1"

  on_macos do
    on_intel do
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Darwin_x86_64.tar.gz"
      sha256 "bffe1579939a74b26bda26e9a1170b78bbf6838df24e7e1965b2cfb929a6ade1"
    end
    on_arm do
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Darwin_arm64.tar.gz"
      sha256 "18fabb098aca41ff8d6a119de512940494a1cfd4cc6f61c1b5e3e03bd93c99d5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Linux_x86_64.tar.gz"
      sha256 "b353d06b2e4d0b0ab7b90d14b4f806e8414d4d9ed8c78157a54a58c01292bf70"
    end
    on_arm do
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Linux_arm64.tar.gz"
      sha256 "d7edd41eb9f8af9e3cebf1042be575e92d62bf9d9d3e833730d06df027014e3c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hulak"]
    end
  end

  caveats do
    "The binary is not signed or notarized. macOS quarantine has been automatically removed."
  end

  # No zap stanza required
end
