# This file was generated by GoReleaser. DO NOT EDIT.
cask "hulak" do
  version "0.3.20"

  on_macos do
    on_intel do
      sha256 "b88cdd3f1b21bc7c7c7c9d0581259bc97ed3de1b90125b8a4b35829f19801ca3"
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3f7bc20c57d7c61a8321be07588a975f8dd35721966559d322d4dddd95e87e87"
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bc902a1be21cb7094847b725f0799338d924dfd17a93a2cc855ba610c95037a3"
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2ce5a6340a65bd008dc99d1b189b6df515e7a0c38a1e8ad3261f1e1160b1817c"
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "hulak"
  desc "File based API client for terminal nerds"
  homepage "https://github.com/xaaha/hulak"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hulak"
  manpage "man/hulak.1"
  bash_completion "completions/hulak.bash"
  zsh_completion "completions/hulak.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hulak"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed or notarized. macOS quarantine has been automatically removed.
  EOS
end
