# This file was generated by GoReleaser. DO NOT EDIT.
cask "hulak" do
  version "0.3.02"

  on_macos do
    on_intel do
      sha256 "ecb38d08a65fabfa7444c93e09809eae2a09724a2c2335f2b5e9d3c8ae1ea2c9"
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "111b98e5b2d60fd25026dc354f0c697fcd9660cf0b4f75aa64162f3661f166fd"
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c942e330cd35bc9fed353eb3cf928ec635c196833d79d5372eef29e9b3953fdc"
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bf9980689d862ef79a789fc0c2c06347bf59c9f22c1fc4dec3e85975be06471a"
      url "https://github.com/xaaha/hulak/releases/download/v#{version}/hulak_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "hulak"
  desc "File based API client for terminal nerds"
  homepage "https://github.com/xaaha/hulak"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hulak"
  manpage "man/hulak.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hulak"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed or notarized. macOS quarantine has been automatically removed.
  EOS
end
